import json

nb = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": []},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"}
    },
    "cells": []
}

def md(src):
    nb["cells"].append({"cell_type": "markdown", "metadata": {}, "source": src})

def code(src):
    nb["cells"].append({"cell_type": "code", "metadata": {}, "source": src, "execution_count": None, "outputs": []})

# Title
md([
    "# Tool-Discovery Agent\n",
    "\n",
    "Discover bioinformatics tools from papers, inject them into your agent, and run tasks.\n",
    "\n",
    "**Flow:** Scan agent -> Inject tools -> Run tasks via downstream agent"
])

# Step 0
code([
    "import os, sys, subprocess\n",
    "ST2_DIR = '/content/st2'\n",
    "if os.path.isdir(os.path.join(ST2_DIR, '.git')):\n",
    "    subprocess.run(['git', '-C', ST2_DIR, 'pull', '--ff-only'], capture_output=True)\n",
    "else:\n",
    "    if os.path.exists(ST2_DIR):\n",
    "        subprocess.run(['rm', '-rf', ST2_DIR], check=True)\n",
    "    subprocess.run(['git', 'clone', '--depth', '1',\n",
    "                    'https://github.com/caixiaoyao2025/st2.git', ST2_DIR], check=True)\n",
    "ST2_DIR = '/content/st2'\n",
    "sys.path.insert(0, ST2_DIR)\n",
    "os.chdir(ST2_DIR)\n",
    "!pip install -q langchain langchain-openai langgraph pydantic graph-tool-call 2>/dev/null || true\n",
    "from IPython.display import display, Markdown\n",
    "display(Markdown('**Setup done**'))"
])

# Step 1 - with widgets AND known agents dict
md(["## Step 1 - Input your agent & API key"])
code([
    "import os, subprocess\n",
    "from IPython.display import display, Markdown\n",
    "import ipywidgets as widgets\n",
    "\n",
    "# ---- Known agent mappings: method + register method ----\n",
    "KNOWN_AGENTS = {\n",
    "    'biomni': {'method': 'go', 'register': 'add_tool'},\n",
    "    'cellagent': {'method': 'run', 'register': 'add_tool'},\n",
    "    'geneagent': {'method': 'run', 'register': 'add_tool'},\n",
    "    'crispr': {'method': 'run', 'register': 'add_tool'},\n",
    "    'biochatter': {'method': 'run', 'register': 'add_tool'},\n",
    "    'langchain': {'method': 'invoke', 'register': 'add_tool'},\n",
    "    'smolagents': {'method': 'run', 'register': 'add_tool'},\n",
    "    'dspy': {'method': 'forward', 'register': 'add_tool'},\n",
    "    'crewai': {'method': 'kickoff', 'register': 'add_tool'},\n",
    "    'metagpt': {'method': 'run', 'register': 'add_tool'},\n",
    "}\n",
    "PROBE_ORDER = ['go', 'run', 'execute', 'predict', 'forward', 'invoke']\n",
    "\n",
    "path_input = widgets.Text(\n",
    "    value='https://github.com/snap-stanford/Biomni.git',\n",
    "    placeholder='Git URL or /content/my_agent',\n",
    "    description='Agent:', layout=widgets.Layout(width='90%'))\n",
    "key_input = widgets.Password(\n",
    "    value='', placeholder='ark-... or sk-...',\n",
    "    description='API Key:', layout=widgets.Layout(width='90%'))\n",
    "model_input = widgets.Text(\n",
    "    value='deepseek-v4-flash-ga-260731',\n",
    "    description='Model:', layout=widgets.Layout(width='70%'))\n",
    "base_input = widgets.Text(\n",
    "    value='https://ark.cn-beijing.volces.com/api/v3',\n",
    "    description='Base URL:', layout=widgets.Layout(width='90%'))\n",
    "btn = widgets.Button(description='Connect agent', button_style='primary')\n",
    "out = widgets.Output()\n",
    "\n",
    "def on_connect(_):\n",
    "    out.clear_output()\n",
    "    with out:\n",
    "        agent_src = path_input.value.strip()\n",
    "        api_key = key_input.value.strip()\n",
    "        model = model_input.value.strip()\n",
    "        base_url = base_input.value.strip()\n",
    "        if not agent_src:\n",
    "            display(Markdown('**ERROR:** Enter agent path or URL')); return\n",
    "        if not api_key:\n",
    "            display(Markdown('**ERROR:** Enter API key')); return\n",
    "        if agent_src.startswith('http'):\n",
    "            agent_dir = '/content/_agent_' + agent_src.split('/')[-1].replace('.git', '')\n",
    "            if not os.path.isdir(agent_dir):\n",
    "                subprocess.run(['git', 'clone', '--depth', '1', agent_src, agent_dir],\n",
    "                               capture_output=True, text=True)\n",
    "            display(Markdown(f'Cloned to `{agent_dir}`'))\n",
    "        else:\n",
    "            agent_dir = agent_src\n",
    "            if not os.path.isdir(agent_dir):\n",
    "                display(Markdown(f'**ERROR:** `{agent_dir}` not found')); return\n",
    "        os.environ['OPENAI_API_KEY'] = api_key\n",
    "        os.environ['OPENAI_BASE_URL'] = base_url\n",
    "        os.environ['OPENAI_MODEL'] = model\n",
    "        os.environ['WESTLAKE_API_KEY'] = api_key\n",
    "        get_ipython().user_ns['agent_dir'] = agent_dir\n",
    "        get_ipython().user_ns['api_key_val'] = api_key\n",
    "        get_ipython().user_ns['model_val'] = model\n",
    "        get_ipython().user_ns['base_url_val'] = base_url\n",
    "        display(Markdown(f'**Agent:** `{agent_dir}` | **Model:** `{model}` | **Key:** `{api_key[:8]}...`'))\n",
    "\n",
    "btn.on_click(on_connect)\n",
    "display(widgets.VBox([path_input, key_input, model_input, base_input, btn, out]))"
])

# Step 2
md(["## Step 2 - Scan agent & detect wiring"])
code([
    "import os, sys, json\n",
    "from IPython.display import display, Markdown\n",
    "import yaml\n",
    "\n",
    "from agent_connector.scanner import build_schema\n",
    "\n",
    "schema = build_schema(agent_dir, include_evidence=False)\n",
    "detected = [\n",
    "    '**Detected:**',\n",
    "    '- agent_class = `' + str(schema.get('agent_class', 'N/A')) + '`',\n",
    "    '- module_path = `' + str(schema.get('module_path', 'N/A')) + '`',\n",
    "    '- registration_method = `' + str(schema.get('registration_method', 'N/A')) + '`',\n",
    "    '- wiring_style = `' + str(schema.get('wiring_style', 'N/A')) + '`',\n",
    "    '- init_signature = `' + str(schema.get('init_signature', 'N/A')) + '`',\n",
    "]\n",
    "display(Markdown('<br>'.join(detected)))\n",
    "\n",
    "reg_path = os.path.join(ST2_DIR, 'data', 'mcp_registry.yaml')\n",
    "tools = yaml.safe_load(open(reg_path, encoding='utf-8'))['tools']\n",
    "display(Markdown(f'**Registry:** {len(tools)} tools'))"
])

# Step 3
md(["## Step 3 - Resolve execution method"])
code([
    "from IPython.display import display, Markdown\n",
    "\n",
    "agent_class = (schema.get('agent_class') or '').lower()\n",
    "\n",
    "# Layer 1: known agent -> direct mapping\n",
    "exec_method = None\n",
    "for pat, info in KNOWN_AGENTS.items():\n",
    "    if pat in agent_class or pat in agent_dir.lower():\n",
    "        exec_method = info['method']\n",
    "        display(Markdown(f'**Known agent** `{pat}` -> `{exec_method}`'))\n",
    "        break\n",
    "\n",
    "# Layer 2: scan source for .go()/.run() hints\n",
    "if exec_method is None:\n",
    "    hits = {}\n",
    "    for root, dirs, files in os.walk(agent_dir):\n",
    "        dirs[:] = [d for d in dirs if d not in ('.git','__pycache__','node_modules','.venv')]\n",
    "        for f in files:\n",
    "            if f.endswith('.py'):\n",
    "                try:\n",
    "                    text = open(os.path.join(root,f), encoding='utf-8', errors='replace').read()\n",
    "                except: continue\n",
    "                for m in PROBE_ORDER:\n",
    "                    hits[m] = hits.get(m, 0) + text.count(f'.{m}(')\n",
    "    if any(v > 0 for v in hits.values()):\n",
    "        exec_method = max(hits, key=hits.get)\n",
    "        display(Markdown(f'**Source hint** -> `{exec_method}` ({hits[exec_method]} occurrences)'))\n",
    "\n",
    "# Layer 3: default\n",
    "if exec_method is None:\n",
    "    exec_method = 'run'\n",
    "    display(Markdown('**No signal found.** Defaulting to `run`.'))\n",
    "\n",
    "get_ipython().user_ns['exec_method_override'] = exec_method"
])

# Step 4
md(["## Step 4 - Preflight check & install"])
code([
    "import os\n",
    "from IPython.display import display, Markdown\n",
    "from agent_connector.agent_preflight import preflight, preflight_report\n",
    "\n",
    "pf = preflight(agent_dir)\n",
    "display(Markdown(preflight_report(pf)))"
])
code([
    "import subprocess, os, sys\n",
    "from IPython.display import display, Markdown\n",
    "\n",
    "if pf.status == 'SETUP_REQUIRED':\n",
    "    pkgs = pf.pip_installable\n",
    "    if pkgs:\n",
    "        display(Markdown(f'Installing **{len(pkgs)}** packages...'))\n",
    "        cmd = [sys.executable, '-m', 'pip', 'install', '-q'] + pkgs\n",
    "        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)\n",
    "        display(Markdown(f'**Done** (returncode={r.returncode})'))\n",
    "    else:\n",
    "        display(Markdown('No auto-installable packages'))\n",
    "else:\n",
    "    display(Markdown(f'Status = `{pf.status}`'))"
])

# Step 5
md(["## Step 5 - Create agent & inject tools"])
code([
    "import os, sys, json, importlib\n",
    "from IPython.display import display, Markdown\n",
    "\n",
    "from agent_connector.generator import generate_wiring, load_wrappers, load_adapter\n",
    "\n",
    "schema['execution_method'] = exec_method_override\n",
    "\n",
    "# Generate wiring (creates adapter with create_agent() using scanner-extracted module_path + init_defaults)\n",
    "wiring_dir = os.path.join(ST2_DIR, 'wiring')\n",
    "wiring = generate_wiring(tools, schema, out_dir=wiring_dir)\n",
    "display(Markdown('Wiring mode: `' + wiring['mode'] + '`'))\n",
    "\n",
    "# Load wrappers\n",
    "sys.path.insert(0, wiring_dir)\n",
    "sys.path.insert(0, agent_dir)\n",
    "reg_style = schema.get('registration_style') or 'object'\n",
    "wrappers = load_wrappers(package_name='generated_tools', registration_style=reg_style)\n",
    "for w in wrappers:\n",
    "    if not hasattr(w, 'name'): w.name = getattr(w, '__name__', None)\n",
    "display(Markdown(f'**{len(wrappers)} wrappers loaded**'))\n",
    "\n",
    "# Create agent via adapter (uses module_path + init defaults from scanner)\n",
    "agent = None\n",
    "adapter = None\n",
    "\n",
    "if schema.get('module_path') or schema.get('registration_method'):\n",
    "    try:\n",
    "        adapter = load_adapter(schema.get('agent_class') or 'Agent',\n",
    "                               adapter_path=wiring['artifacts']['adapter'])\n",
    "        agent = adapter.create_agent()\n",
    "        adapter.register_tools(agent, wrappers)\n",
    "        display(Markdown(f'**Agent created via adapter:** `{type(agent).__name__}`'))\n",
    "    except Exception as e:\n",
    "        display(Markdown(f'`create_agent()` failed: `{e}`'))\n",
    "\n",
    "# Fallback: DynamicAgent\n",
    "if agent is None:\n",
    "    class DynamicAgent:\n",
    "        def __init__(self): self.tools = []\n",
    "    DynamicAgent.add_tool = lambda self, t: self.tools.append(t)\n",
    "    agent = DynamicAgent()\n",
    "    for w in wrappers: agent.add_tool(w)\n",
    "    display(Markdown(f'**Fallback:** DynamicAgent with {len(agent.tools)} tools'))\n",
    "\n",
    "# Verify exec method on agent\n",
    "is_known = any(pat in agent_dir.lower() or pat in type(agent).__name__.lower()\n",
    "               for pat in KNOWN_AGENTS)\n",
    "if is_known:\n",
    "    display(Markdown(f'**Known agent** -> method `{exec_method_override}` (trusted)'))\n",
    "else:\n",
    "    probe = None\n",
    "    for m in PROBE_ORDER:\n",
    "        if m == '__call__':\n",
    "            if callable(agent): probe = m; break\n",
    "        elif hasattr(agent, m) and callable(getattr(agent, m)):\n",
    "            probe = m; break\n",
    "    if probe:\n",
    "        display(Markdown(f'**Probe OK:** `agent.{probe}()` exists'))\n",
    "        get_ipython().user_ns['exec_method_override'] = probe\n",
    "    else:\n",
    "        tried = ', '.join(f'`{m}()`' for m in PROBE_ORDER)\n",
    "        display(Markdown(f'**Probe FAILED:** tried {tried}'))\n",
    "        display(Markdown('Go to **Step 5b** to provide your agent init code manually.'))\n",
    "\n",
    "get_ipython().user_ns['agent'] = agent\n",
    "get_ipython().user_ns['wrappers'] = wrappers\n",
    "get_ipython().user_ns['adapter'] = adapter"
])

# Step 5b
md([
    "## Step 5b - Manual agent init (only if Step 5 failed)\n",
    "\n",
    "If Step 5 succeeded, **skip this cell**."
])
code([
    "from IPython.display import display, Markdown\n",
    "import ipywidgets as widgets\n",
    "\n",
    "already_ok = is_known\n",
    "if not already_ok:\n",
    "    for m in PROBE_ORDER:\n",
    "        if m == '__call__':\n",
    "            if callable(agent): already_ok = True; break\n",
    "        elif hasattr(agent, m) and callable(getattr(agent, m)):\n",
    "            already_ok = True; break\n",
    "\n",
    "if already_ok:\n",
    "    display(Markdown('Step 5 succeeded. **Skipping.**'))\n",
    "else:\n",
    "    display(Markdown('### Agent execution method not recognized\\n\\n'\n",
    "        '**Tried:** ' + ', '.join(f'`{m}`' for m in PROBE_ORDER) + '\\n\\n'\n",
    "        '**Please paste your agent init code below:**'))\n",
    "    code_area = widgets.Textarea(\n",
    "        value='# from my_agent import MyAgent\\n# agent = MyAgent(model=\"gpt-4\")\\n# agent.add_tools(wrappers)\\n',\n",
    "        placeholder='agent = MyAgent(...)',\n",
    "        layout=widgets.Layout(width='90%', height='150px'))\n",
    "    method_input = widgets.Dropdown(\n",
    "        options=['run', 'execute', 'go', 'predict', 'forward', 'invoke', '__call__'],\n",
    "        value='run', description='Exec method:', layout=widgets.Layout(width='60%'))\n",
    "    apply_btn = widgets.Button(description='Apply', button_style='primary')\n",
    "    out = widgets.Output()\n",
    "\n",
    "    def on_apply(_):\n",
    "        out.clear_output()\n",
    "        with out:\n",
    "            try:\n",
    "                local_ns = {'wrappers': wrappers, 'agent_dir': agent_dir}\n",
    "                exec(code_area.value, local_ns)\n",
    "                new_agent = local_ns.get('agent')\n",
    "                if new_agent is None:\n",
    "                    display(Markdown('Error: no `agent` variable found.')); return\n",
    "                method = method_input.value\n",
    "                fn = getattr(new_agent, method, None) if method != '__call__' else new_agent\n",
    "                if fn is None or not callable(fn):\n",
    "                    display(Markdown(f'Error: `{method}` not callable.')); return\n",
    "                get_ipython().user_ns['agent'] = new_agent\n",
    "                get_ipython().user_ns['exec_method_override'] = method\n",
    "                agent = new_agent\n",
    "                display(Markdown(f'**Done!** Agent=`{type(new_agent).__name__}` method=`{method}`'))\n",
    "            except Exception as e:\n",
    "                display(Markdown(f'Error: `{e}`'))\n",
    "\n",
    "    apply_btn.on_click(on_apply)\n",
    "    display(widgets.VBox([code_area, method_input, apply_btn, out]))"
])

# Step 6
md([
    "## Step 6 - Run tasks via downstream agent\n",
    "\n",
    "Your query is sent to the agent via `agent.{method}(query)`. The agent uses the injected tools internally."
])
code([
    "from IPython.display import display, Markdown\n",
    "import ipywidgets as widgets\n",
    "import time\n",
    "\n",
    "method = exec_method_override\n",
    "if method == '__call__':\n",
    "    exec_fn = agent\n",
    "else:\n",
    "    exec_fn = getattr(agent, method, None)\n",
    "\n",
    "if exec_fn is None or not callable(exec_fn):\n",
    "    display(Markdown(f'ERROR: `agent.{method}()` not callable'))\n",
    "else:\n",
    "    display(Markdown(f'Ready: `agent.{method}()`'))\n",
    "\n",
    "query_input = widgets.Text(\n",
    "    value='Analyze the FASTA file at /content/sample.fasta',\n",
    "    placeholder='Ask a bioinformatics question...',\n",
    "    description='Query:', layout=widgets.Layout(width='95%'))\n",
    "run_btn = widgets.Button(description='Run agent', button_style='success')\n",
    "result_out = widgets.Output()\n",
    "\n",
    "def run_query(_):\n",
    "    result_out.clear_output()\n",
    "    with result_out:\n",
    "        query = query_input.value.strip()\n",
    "        if not query:\n",
    "            display(Markdown('**Enter a query**')); return\n",
    "        display(Markdown(f'**Query:** {query}'))\n",
    "        display(Markdown(f'**Calling:** `agent.{method}(query)` ...'))\n",
    "        t0 = time.time()\n",
    "        try:\n",
    "            result = exec_fn(query)\n",
    "            elapsed = time.time() - t0\n",
    "            display(Markdown(f'**Done** ({elapsed:.1f}s)'))\n",
    "            if isinstance(result, str):\n",
    "                display(Markdown(f'### Result\\n{result}'))\n",
    "            else:\n",
    "                display(Markdown(f'### Result\\n```\\n{str(result)[:2000]}\\n```'))\n",
    "        except Exception as e:\n",
    "            display(Markdown(f'**Error:** `{type(e).__name__}: {e}`'))\n",
    "\n",
    "run_btn.on_click(run_query)\n",
    "display(widgets.VBox([query_input, run_btn, result_out]))"
])

with open('interactive_agent.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Done: {len(nb['cells'])} cells")
