"""Test whether a real downstream agent (LLM) can correctly use auto-discovered tools.

Reads data/mcp_registry.yaml (tools discovered + validated by the pipeline),
converts them to OpenAI function schemas, then runs a real function-calling loop
with an OpenAI-compatible LLM (volcengine Ark / DeepSeek). The LLM must:
  1. pick the right tool from the schema
  2. pass correct arguments (from the --help-parsed inputs)
  3. the tool auto-installs its environment (run_tool_spec _ensure_installed)
  4. returns a correct result

Env vars:
  WESTLAKE_API_KEY   (or OPENAI_API_KEY / DEEPSEEK_API_KEY)
  WESTLAKE_BASE_URL  (default https://ark.cn-beijing.volces.com/api/v3)
  WESTLAKE_MODEL     (default doubao-seed-evolving)
  REGISTRY           (default data/mcp_registry.yaml)
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time

REPO = os.path.dirname(os.path.abspath(__file__))
if REPO not in sys.path:
    sys.path.insert(0, REPO)

import yaml  # noqa: E402

from agent_connector.tool_spec import (  # noqa: E402
    canonical_key, function_anyof, function_property, json_schema_type, make_leaf_spec,
)
from agent_connector.artifact_spec import ARTIFACT_TYPES, infer_artifact_from_description  # noqa: E402

BASE_URL = (os.environ.get("WESTLAKE_BASE_URL") or os.environ.get("OPENAI_BASE_URL")
            or os.environ.get("DEEPSEEK_BASE_URL")
            or "https://ark.cn-beijing.volces.com/api/v3")
MODEL = (os.environ.get("WESTLAKE_MODEL") or os.environ.get("OPENAI_MODEL")
          or os.environ.get("DEEPSEEK_MODEL") or "deepseek-v4-flash-ga-260731")
API_KEY = (os.environ.get("WESTLAKE_API_KEY") or os.environ.get("OPENAI_API_KEY")
           or os.environ.get("DEEPSEEK_API_KEY") or "")
REGISTRY = os.environ.get("REGISTRY", "data/mcp_registry.yaml")
MAX_TURNS = 6
MAX_SAME_TOOL_ATTEMPTS = 3  # anti-tool-roulette: cap retries per tool per task
# A tool that HANGS (bioemu waiting on an unreachable model hub) must fail fast
# and let the agent move on -- otherwise a single hung subprocess eats the
# spec default 600s per call and the whole step times out (run #31941212195).
AGENT_CALL_TIMEOUT = 600   # seconds per tool invocation in the agent harness
AGENT_TASK_BUDGET = 900    # seconds per task (all turns combined)
AGENT_LLM_TIMEOUT = 180    # seconds per chat.completions call (SDK timeout)

# bqtools derives the output MODE from the -o path EXTENSION (*.bq/*.vbq/*.cbq),
# so file-producing subcommand outputs need a real extension (.binseq errors
# "Could not determine BINSEQ output mode from path"). BINSEQ-consuming
# subcommands need a *.vbq input, NOT the FASTA sample (a FASTA fed to decode/
# grep/etc fails "Unable to determine BINSEQ format from magic bytes").
_BQ_OUT_EXT = {"encode": ".vbq", "cat": ".vbq", "grep": ".fa",
               "sample": ".fa", "revcomp": ".vbq", "decode": ".fa"}
_BQ_INPUT_BINSEQ = ("decode", "cat", "info", "grep", "sample", "split",
                     "pipe", "revcomp", "verify")

# ---------------------------------------------------------------------------
# Artifact-aware fixture system
# ---------------------------------------------------------------------------
# Maps artifact_type -> (file extension, minimal valid content).
# The agent test generates ONE fixture per artifact type and reuses it across
# all tools that need that format. This replaces the old universal FASTA.
_FIXTURE_CONTENT: dict[str, tuple[str, str]] = {
    "fasta": (".fasta", ">seq1\nACGTACGT\n>seq2\nTTTTTTTT\n"),
    "fastq": (".fastq", "@read1\nACGTACGT\n+\nIIIIIIII\n"),
    "binseq": (".vbq", ""),  # generated by bqtools encode at runtime
    "bed": (".bed", "chr1\t100\t200\tfeature1\nchr1\t300\t400\tfeature2\n"),
    "bedpe": (".bedpe", "chr1\t100\t200\tchr1\t300\t400\tfeature1\n"),
    "vcf": (".vcf", "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\nchr1\t100\t.\tA\tG\t.\tPASS\t.\n"),
    "bam": (".bam", ""),  # placeholder - real tool needs actual binary
    "sam": (".sam", "@HD\tVN:1.6\tSO:coordinate\nread1\t0\tchr1\t100\t60\t4M\t*\t0\t0\tACGT\t*\n"),
    "cool_matrix": (".cool", ""),  # placeholder - needs cooler create
    "mcool": (".mcool", ""),
    "genomic_features": (".bed", "chr1\t100\t200\tfeature1\nchr1\t300\t400\tfeature2\n"),
    "expected_matrix": (".tsv", "region1\tregion2\t0.5\n"),
    "bigwig": (".bw", ""),
    "pdb": (".pdb", "ATOM      1  N   ALA A   1       1.000   1.000   1.000  1.00           N\n"),
    "json": (".json", '{"key": "value"}\n'),
    "text": (".txt", "col1\tcol2\tcol3\nval1\tval2\tval3\n"),
}

# Cache: artifact_type -> fixture path (generated once, reused)
_fixture_cache: dict[str, str] = {}


def _ensure_fixtures(fixture_dir: str) -> None:
    """Generate all known fixture files in fixture_dir."""
    os.makedirs(fixture_dir, exist_ok=True)
    for artifact, (ext, content) in _FIXTURE_CONTENT.items():
        if artifact in _fixture_cache:
            continue
        path = os.path.join(fixture_dir, f"sample_{artifact}{ext}")
        if not os.path.exists(path) and content:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
        _fixture_cache[artifact] = path


def _fixture_for_artifact(artifact_type: str) -> str | None:
    """Return the fixture path for an artifact type, or None."""
    return _fixture_cache.get(artifact_type)


def _resolve_param_fixtures(leaf: dict) -> dict[str, str]:
    """Resolve a fixture path for each INPUT file-type parameter in a leaf spec.

    Returns {param_key: fixture_path} for required file/path INPUT params only.
    Skips output params, runtime resources, booleans, integers.
    """
    result = {}
    output_keys = set(leaf.get("outputs") or {})
    resource_keys = set(leaf.get("resources") or {})
    inputs = leaf.get("inputs") or {}
    for key, meta in inputs.items():
        if not isinstance(meta, dict):
            continue
        if key in output_keys or key in resource_keys:
            continue
        if not meta.get("required"):
            continue
        jtype = meta.get("type", "string")
        if jtype not in ("string", "path", "file"):
            continue
        artifact = meta.get("artifact_type") or meta.get("artifact")
        if artifact and artifact != "directory":
            path = _fixture_for_artifact(artifact)
            if path and os.path.exists(path):
                result[key] = path
                continue
        # No artifact annotation but it's a required file param — use sample
        result[key] = os.path.join(tempfile.gettempdir(), "agent_test_sample.fasta")
    return result


def _build_subcommand_prompt(fn_name: str, tool_name: str,
                             param_fixtures: dict[str, str],
                             out_path: str, out_param: str | None,
                             sub: str = "", pattern_file: str = "") -> str:
    """Build a task prompt that tells the LLM exactly which fixture to use
    for each parameter, instead of giving it a single file for everything."""
    lines = [f"Call the function {fn_name} (NOT {tool_name} directly)."]
    # List each parameter with its fixture path
    for param_key, fixture_path in sorted(param_fixtures.items()):
        artifact = ""
        # Try to find the artifact type from the fixture filename
        for atype, (ext, _) in _FIXTURE_CONTENT.items():
            if fixture_path.endswith(f"_{atype}{ext}"):
                artifact = f" ({atype})"
                break
        lines.append(f"  - Use '{fixture_path}' as the '{param_key}' parameter{artifact}.")
    # Output parameter
    if out_param:
        lines.append(f"  - Write the output to '{out_path}' as the '{out_param}' parameter.")
    # Subcommand-specific constraints
    if sub == "split":
        lines.append(f"  - The function requires at least one pattern file -- "
                     f"use '{pattern_file}' as the 'file' parameter.")
    if sub == "pipe":
        lines.append('  - The --exec parameter MUST contain "{}" which is replaced '
                     'by the FIFO path. Example: --exec "cat {}".')
    lines.append("After running, the output must exist (if output param was provided) "
                 "or report what it printed (if stdout).")
    return "\n".join(lines)


def _build_nonsubcommand_prompt(tool_name: str, param_fixtures: dict[str, str],
                                out_path: str, out_param: str | None) -> str:
    """Build a task prompt for non-subcommand tools with per-param fixtures."""
    lines = [f"Call the {tool_name} tool."]
    for param_key, fixture_path in sorted(param_fixtures.items()):
        lines.append(f"  - Use '{fixture_path}' as the '{param_key}' parameter.")
    if out_param:
        lines.append(f"  - Write the output to '{out_path}' as the '{out_param}' parameter.")
    lines.append("Aim for exit code 0. Report what it prints if no output file.")
    return "\n".join(lines)


def load_tools(path: str) -> list[dict]:
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    tools = data.get("tools", [])
    return [t for t in tools if isinstance(t, dict) and t.get("name")]


# tokens that indicate a broken/mis-parsed schema. `{{var}}` template
# variables are LEGAL (command placeholders) -- we strip them before checking,
# and only flag real pollution: ANSI escapes, argparse choices `{a,b}` used as
# a name, `[OPTIONS]/[ARGS]` usage text, ellipsis pseudo-tokens.
_TEMPLATE_VAR = re.compile(r"\{\{[a-zA-Z_][a-zA-Z0-9_]*\}\}")
# capture the variable NAME so we can cross-check it against the input schema
_TEMPLATE_VAR_NAME = re.compile(r"\{\{([a-zA-Z_][a-zA-Z0-9_]*)\}\}")
_POLLUTION = re.compile(r"\x1b\[|\.\.\.|\[OPTIONS\]|\[ARGS\]|\bCOMMAND\b|^\.$")
# argparse choices leaked as a parameter key: `{init,check,...}` (not {{var}})
_CHOICES_KEY = re.compile(r"\{[a-zA-Z0-9_,\-\s]+\}")


def _clean_template(command: str) -> str:
    """Replace legal {{var}} placeholders so they don't look like pollution."""
    return _TEMPLATE_VAR.sub("PLACEHOLDER", command)


def validate_tool_schema(tool: dict) -> str:
    """Return '' if the tool's schema is clean enough to give an LLM, else a
    reason (SCHEMA_INVALID / NO_CMD / SUBCOMMAND_INCOMPLETE / R_PACKAGE)."""
    name = tool.get("name", "")
    cmd = tool.get("command") or ""
    as_ = tool.get("arg_style") or "cli"
    inputs = tool.get("inputs") or {}
    # broken command template: check after masking legal {{var}} placeholders
    if _POLLUTION.search(_clean_template(cmd)):
        return f"SCHEMA_INVALID: command polluted ({cmd[:40]})"
    # broken input names: {{var}} is never a legal input KEY; choices `{a,b}`
    # as a key is pollution from argparse subparsers
    for k in inputs.keys():
        if _POLLUTION.search(k) or _TEMPLATE_VAR.search(k) or _CHOICES_KEY.search(k):
            return f"SCHEMA_INVALID: input name polluted ({k!r})"
    if not cmd.strip():
        return "NO_CMD"
    # template variable <-> input schema consistency: every {{var}} in the
    # command must have a matching input OR declared resource (resources are
    # injected by the runner, not LLM args -- kaptain's {{db}} is a KMA
    # database path), or the rendered argv is undefined.
    vars_used = _TEMPLATE_VAR_NAME.findall(cmd)
    declared_names = set(inputs.keys()) | set((tool.get("resources") or {}).keys())
    unknown = [v for v in vars_used if v not in declared_names]
    if unknown:
        return f"SCHEMA_INVALID: unknown template variable {sorted(set(unknown))} (command {cmd[:60]})"
    # R package / python_import without -m: not directly callable as a command
    if as_ == "python" and not (tool.get("callable_via") or "").startswith("python -m "):
        return "R_PACKAGE_OR_IMPORT"
    if as_ == "subcommand" and not tool.get("subcommand_discovery_complete"):
        return "SUBCOMMAND_INCOMPLETE"
    return ""


def to_function_schemas(tool: dict) -> tuple[list[dict], dict]:
    """Build OpenAI function schema(s) for a tool.

    For subcommand CLIs we expand each subcommand into its OWN function so the
    agent picks `bqtools_encode(input, output)` instead of guessing a
    `subcommand` argument. Returns (schemas, fnmap) where fnmap maps the
    function name -> the EXACT leaf ToolSpec to execute -- make_leaf_spec is
    the single source of truth, so the spec the LLM was shown and the spec
    handed to run_tool_spec are the SAME object (never a base-tool re-parse).
    """
    fnmap: dict = {}
    if (tool.get("arg_style") == "subcommand") and tool.get("subcommand_details"):
        out = []
        for sub, detail in (tool.get("subcommand_details") or {}).items():
            # P0: build the leaf spec FIRST (make_leaf_spec is the SINGLE
            # source of truth for a subcommand's inputs -- positional metadata,
            # flag spelling, required semantics, outputs contract) and derive
            # the function schema from ITS `inputs`. Deriving props straight
            # from `subcommand_details[sub].params` re-infers the contract and
            # can drift (e.g. a positional marked required by make_leaf_spec
            # but optional here -> the LLM schema and the validator disagree).
            leaf = make_leaf_spec(tool, sub)
            props = {}
            required = []
            for key, meta in (leaf.get("inputs") or {}).items():
                props[key] = function_property(meta)
                # ONLY an explicit `required: true` (make_leaf_spec forces it
                # for positionals) makes a param required. A flag with no
                # required marker is OPTIONAL -- forcing every param required
                # would hand the LLM a fake schema (e.g. kaptain with all 15
                # flags required -> LLM fills garbage -> CLI error).
                if (meta or {}).get("required") is True:
                    required.append(key)
            fname = f"{tool['name']}_{sub.replace('-', '_')}"
            params_schema = {"type": "object", "properties": props, "required": required}
            # conditional required: at least one param from each group must be
            # provided (e.g. split needs --file OR --sfile OR --xfile). Emitted
            # as JSON Schema ``anyOf`` so the LLM sees the constraint.
            ao = function_anyof(leaf)
            if ao:
                params_schema["anyOf"] = [
                    {"required": grp} for grp in ao if grp
                ]
            out.append({"type": "function", "function": {
                "name": fname,
                "description": _function_description(leaf),
                "parameters": params_schema,
            }})
            fnmap[fname] = leaf
        return out, fnmap
    # non-subcommand: single function
    props = {}
    required = []
    for name, meta in (tool.get("inputs") or {}).items():
        props[name] = function_property(meta)
        # ONLY an explicit `required: true` is required. Auto-discovery cannot
        # reliably know which flags are mandatory, so defaulting to optional is
        # the honest schema (a guessed-required list is worse: the LLM invents
        # values for flags the tool doesn't need).
        if (meta or {}).get("required") is True:
            required.append(name)
    fn = {"type": "function", "function": {
        "name": tool["name"],
        "description": _function_description(tool),
        "parameters": {"type": "object", "properties": props, "required": required},
    }}
    # execution infrastructure (install/venv/command) is NOT tool-call semantics
    # for the LLM; keep only arg_style as a hint.
    if tool.get("arg_style"):
        fn["function"]["arg_style"] = tool["arg_style"]
    fnmap[tool["name"]] = tool
    return [fn], fnmap


def _function_description(tool: dict) -> str:
    """Tool description PLUS the runtime-resource contract, the output
    contract, and any conditional-required constraints, so the LLM knows
    (a) a database/index path is PRECONFIGURED -- never guessed, never an
    argument it must invent -- (b) what the tool produces and where
    (output_dir -> directory), and (c) which parameter groups must be
    provided together."""
    desc = (tool.get("description") or "")
    resources = tool.get("resources") or {}
    if resources:
        names = ", ".join(sorted(resources))
        desc = (desc.strip() + " "
                + f"Runtime resources are preconfigured and must NOT be passed "
                  f"as arguments: {names}.")
    # conditional required constraint hint
    ao = (tool.get("constraints") or {}).get("any_of") or []
    if ao:
        groups = " OR ".join(", ".join(g) for g in ao if g)
        desc = (desc.strip() + " "
                + f"Requires at least one of: {groups}.").strip()
    # exec template constraint: the --exec string MUST contain "{}" which is
    # replaced by the FIFO pipe path. Without it, the CLI rejects the call.
    exec_constraint = (tool.get("constraints") or {}).get("exec_template") or {}
    if exec_constraint.get("contains") == "{}":
        desc = (desc.strip() + " "
                + 'The --exec parameter MUST contain "{}" which is replaced '
                  'by the FIFO path. Example: --exec "cat {}"').strip()
    # artifact type hints: surface what data format each file parameter expects
    # so the LLM doesn't feed FASTA to a Hi-C tool or .cool to a FASTA tool.
    inputs = tool.get("inputs") or {}
    artifact_hints = []
    for key, meta in inputs.items():
        if not isinstance(meta, dict):
            continue
        artifact = meta.get("artifact")
        if artifact and artifact != "directory":
            exts = (meta.get("artifact_info") or {}).get("extensions") or []
            ext_str = "/".join(exts[:3]) if exts else artifact
            artifact_hints.append(f"{key} expects {ext_str}")
    if artifact_hints:
        desc = (desc.strip() + " "
                + "Input formats: " + "; ".join(artifact_hints) + ".").strip()
    outs = tool.get("outputs") or {}
    if isinstance(outs, dict) and outs:
        bits = []
        for name, meta in outs.items():
            if name == "stdout":
                bits.append("stdout (console output)")
                continue
            kind = (meta or {}).get("type", "file") if isinstance(meta, dict) else "file"
            bits.append(f"{name} ({kind})")
        if bits:
            desc = (desc.strip() + " " + f"Produces: {', '.join(bits)}.").strip()
    return desc[:600]


def _task_output_kind(tool: dict, sub: str = "") -> str:
    """Decide what a successful task must produce, from the tool's schema.

    Returns 'file' | 'directory' | 'stdout'. Uses the registry's `outputs`
    contract when present; a declared file/dir output param is the target, and
    tools with no output param are stdout-only (exit 0 + output is the bar).
    """
    outs = (tool.get("outputs") or {}).get(sub, {}) if sub else (tool.get("outputs") or {})
    if not isinstance(outs, dict):
        outs = {}
    if sub and not outs:
        # subcommand output contract lives on the subcommand itself
        # (discovery_to_registry stores it in subcommand_details[sub].outputs),
        # so bqtools_encode's file output is validated as a FILE, not stdout.
        detail = (tool.get("subcommand_details") or {}).get(sub) or {}
        sub_outs = detail.get("outputs") or {}
        if isinstance(sub_outs, dict):
            outs = sub_outs
    for name, meta in outs.items():
        if name == "stdout":
            continue
        t = (meta or {}).get("type", "")
        if t == "directory":
            return "directory"
        if t in ("file", "path"):
            return "file"
    return "stdout"


def _task_output_param(tool: dict, sub: str = "") -> str:
    """The input parameter name that CARRIES the task's output path.

    Returns the canonical input key whose flag/positional the tool writes to
    (bioemu -> 'output_dir', bqtools_encode -> 'output'), or '' if the tool's
    output contract is stdout-only. The task prompt uses this name so the LLM
    passes the output path to the RIGHT parameter instead of guessing.
    """
    outs = (tool.get("outputs") or {}).get(sub, {}) if sub else (tool.get("outputs") or {})
    if not isinstance(outs, dict):
        outs = {}
    if sub and not outs:
        detail = (tool.get("subcommand_details") or {}).get(sub) or {}
        sub_outs = detail.get("outputs") or {}
        if isinstance(sub_outs, dict):
            outs = sub_outs
    for name, meta in outs.items():
        if name == "stdout":
            continue
        t = (meta or {}).get("type", "")
        if t in ("file", "path", "directory"):
            # prefer the explicit outputs[out].input link (the parameter that
            # carries the output path); fall back to the output key itself when
            # an older registry has no explicit association.
            param = (meta or {}).get("input") or name
            inputs = (tool.get("inputs") or {})
            if sub:
                detail = (tool.get("subcommand_details") or {}).get(sub) or {}
                inputs = {canonical_key(p.get("name", "")): p
                          for p in (detail.get("params") or [])}
            if param in inputs:
                return param
    return ""


def ensure_repo() -> None:
    """Make sure the repo + agent_connector are importable and the registry exists.

    In Colab this script may be run standalone, so clone the repo if
    agent_connector isn't importable, and download the registry if missing.
    """
    global REPO, REGISTRY
    try:
        import agent_connector  # noqa: F401
        found = True
    except ImportError:
        found = False
    if not found:
        import subprocess
        dest = "/content/scientific_training2_cxy"
        print("[colab-prep] cloning repo ...")
        subprocess.run(
            ["git", "clone", "--depth", "1",
             "https://github.com/caixiaoyao2025/scientific_training2_cxy.git", dest],
            check=True, capture_output=True, text=True)
        REPO = dest
        if REPO not in sys.path:
            sys.path.insert(0, REPO)
        if REGISTRY == "data/mcp_registry.yaml":
            REGISTRY = os.path.join(dest, REGISTRY)
    if not os.path.exists(REGISTRY) and not os.path.isabs(REGISTRY):
        # try relative to repo
        cand = os.path.join(REPO, REGISTRY)
        if os.path.exists(cand):
            REGISTRY = cand
        else:
            print(f"registry not found at {REGISTRY} - skipping")
            raise SystemExit(0)


def main() -> int:
    if not API_KEY:
        print("no API key (WESTLAKE_API_KEY/OPENAI_API_KEY/DEEPSEEK_API_KEY) - skipping agent test")
        return 0
    ensure_repo()
    if not os.path.exists(REGISTRY):
        print(f"no registry at {REGISTRY} - skipping")
        return 0
    tools = load_tools(REGISTRY)
    if not tools:
        print("registry empty - skipping")
        return 0
    print(f"tools from {REGISTRY}: {[t['name'] for t in tools]}")

    from openai import OpenAI
    from agent_connector.tool_runner import run_tool_spec, format_result
    client = OpenAI(api_key=API_KEY, base_url=BASE_URL,
                    timeout=AGENT_LLM_TIMEOUT, max_retries=1)
    # Only test tools the agent can actually invoke via function-calling:
    # those with a real command (named/positional/subcommand CLI or `python -m`).
    # python_import / python-API tools without a -m entry can't be invoked by a
    # function-calling agent (it can't write import code) - mark and skip them.
    callable_tools = []
    skipped = []
    heavy = ("torch", "tensorflow", "torchvision", "torchaudio", "jax",
             "cupy", "paddle", "triton", "pytorch", "transformers", "diffusers")
    for t in tools:
        cv = t.get("callable_via") or ""
        as_ = t.get("arg_style") or "cli"
        # strict registry validation FIRST: polluted/ambiguous schemas must not
        # reach the LLM (they cause the retry-loop/timeout we saw).
        vres = validate_tool_schema(t)
        if vres:
            skipped.append(t["name"])
            print(f"[skip] {t['name']}: {vres}")
            continue
        # PLACEHOLDER schemas: `inputs_source: placeholder` means the inputs were
        # GUESSED (default `input_file`), never parsed from the tool's --help.
        # Such an entry has no real parameter contract (bqtools is stuck as
        # `bqtools {{input_file}}` because its paper wasn't rediscovered) and
        # must not reach the LLM -- the agent would only flail on it.
        ev = t.get("evidence") or {}
        if ev.get("inputs_source") == "placeholder":
            skipped.append(t["name"])
            print(f"[skip] {t['name']}: placeholder inputs (never --help-parsed; "
                  f"schema is a guess, not a contract)")
            continue
        # heavy ML deps: installing torch on-demand is too slow/unreliable
        decl = (t.get("install") or {}).get("declared_packages") or []
        if any(h in " ".join(decl).lower() for h in heavy):
            skipped.append(t["name"])
            print(f"[skip] {t['name']}: heavy ML deps (torch/tf) - needs preinstall")
            continue
        callable_tools.append(t)
    schemas = []
    fnmap = {}
    for t in callable_tools:
        sch, fm = to_function_schemas(t)
        schemas.extend(sch)
        fnmap.update(fm)
    schema_by_name = {s["function"]["name"]: s for s in schemas}
    # fnmap maps every function name -> the EXACT ToolSpec (leaf) to execute
    # (to_function_schemas). What the LLM was shown and what run_tool_spec
    # receives are the SAME object -- no base-tool re-derivation anywhere.
    if not callable_tools:
        print("no function-callable tools in registry; nothing to test")
        return 0

    # P0: prove the schemas actually sent to the LLM are what we expect BEFORE
    # spending API calls. If a subcommand tool didn't produce its leaf functions
    # (bqtools_encode etc.) that is a pipeline bug, not an agent failure.
    print(f"\n== {len(schemas)} function schemas sent to the LLM ==")
    for s in schemas:
        fn = s["function"]
        params = fn["parameters"]
        line = (f"  {fn['name']:30} params={list(params.get('properties', {}).keys())} "
                f"required={params.get('required')}")
        if params.get("anyOf"):
            line += f" anyOf={params['anyOf']}"
        print(line)
    sub_broken = []
    for t in callable_tools:
        if t.get("arg_style") == "subcommand" and t.get("subcommand_details"):
            for sub in (t.get("subcommand_details") or {}):
                leaf = f"{t['name']}_{sub.replace('-', '_')}"
                if leaf not in fnmap:
                    sub_broken.append(leaf)
    if sub_broken:
        print(f"[ERROR] subcommand tools produced NO leaf function for: {sub_broken}")
        print("        -> registry/subcommand_details is broken; refusing to run LLM")
        return 1
    print("  (all subcommand leaves present in schema)")

    # sample input for tools that take a file path (legacy fallback)
    sample = os.path.join(tempfile.gettempdir(), "agent_test_sample.fasta")
    with open(sample, "w", encoding="utf-8") as f:
        f.write(">seq1\nACGT\nACGT\n>seq2\nTTTTTT\n>seq3\nCCCGGG\n>seq4\nAAAAT\n>seq5\nGATAC\n")
    # real *.vbq fixture for the BINSEQ-consuming subcommands (encode's input is
    # the FASTA). Best-effort: if the binary is missing the binseq tasks fail
    # honestly on a missing file instead of a fake format mismatch.
    binseq_sample = os.path.join(tempfile.gettempdir(), "agent_test_sample.vbq")
    # pattern file for split (requires at least one of --file/--sfile/--xfile)
    pattern_file = os.path.join(tempfile.gettempdir(), "agent_test_pattern.txt")
    with open(pattern_file, "w", encoding="utf-8") as pf:
        pf.write("ACGT\n")
    # artifact-aware fixtures: one per format, generated once, reused across tools
    fixture_dir = os.path.join(tempfile.gettempdir(), "agent_fixtures")
    _ensure_fixtures(fixture_dir)
    if not os.path.exists(binseq_sample):
        # run_tool_spec() prepends venv/bin/ to PATH; shutil.which() won't
        # find bqtools unless we search the venv explicitly.
        _bq_bin = None
        for _t in callable_tools:
            if _t.get("name") == "bqtools":
                _v = (_t.get("install") or {}).get("venv_path", "")
                if _v:
                    _bq_bin = os.path.join(_v, "bin")
                break
        _bq_exe = shutil.which("bqtools") or (shutil.which("bqtools", path=_bq_bin) if _bq_bin else None)
        if _bq_exe:
            _env = os.environ.copy()
            if _bq_bin:
                _env["PATH"] = _bq_bin + os.pathsep + _env.get("PATH", "")
            try:
                subprocess.run(["bqtools", "encode", sample, "--output", binseq_sample],
                               timeout=60, capture_output=True, text=True, check=False,
                               env=_env)
            except Exception:  # noqa: BLE001
                pass

    # --- per-tool concrete tasks with specified params + output validation ---
    # Each task tells the agent the tool, the input file, and a concrete output
    # path to produce. Success = tool exits 0 AND the output file exists. This
    # avoids "invoke it with valid args" (agent guessing) and catches the
    # earlier bqtools "encode but no output" false-positive.
    outdir = os.path.join(tempfile.gettempdir(), "agent_task_out")
    os.makedirs(outdir, exist_ok=True)
    tasks = []
    skip_reasons = []
    for t in callable_tools:
        name = t["name"]
        as_ = t.get("arg_style") or "cli"
        # runtime resources (kaptain's KMA DB, metaphlan DB): the LLM must
        # NEVER guess a database path. A tool whose required resources have no
        # environment path is not executable -- skip its task with a clear
        # reason instead of sending the agent in to flail.
        # Also skip tools where a declared resource has no resolvable path
        # even if not marked required (e.g. MetaPhlAn's db_dir which the CLI
        # says is "optional" but the tool needs at runtime).
        missing_res = []
        for k, r in (t.get("resources") or {}).items():
            r = r or {}
            if r.get("path"):
                continue  # explicitly provisioned in registry
            # check env var: <TOOLNAME>_<RESOURCE_KEY>
            env_name = f"{name}_{k}".upper().replace("-", "_")
            if os.environ.get(env_name):
                continue  # env var is set
            if r.get("required") or r.get("required_by") == "runtime":
                missing_res.append(k)
        if missing_res:
            skip_reasons.append(f"{name}: required runtime resource(s) "
                                f"{sorted(missing_res)} have no environment path")
            continue
        if as_ == "subcommand" and t.get("subcommand_details"):
            # one task PER leaf subcommand function (bqtools_encode / _decode /
            # _info ...), not just the first. Each task is bound to its exact
            # function name so the test can distinguish WRONG_FUNCTION.
            for sub, detail in (t.get("subcommand_details") or {}).items():
                expected_fn = f"{name}_{sub.replace('-', '_')}"
                out = os.path.join(outdir, f"{name}_{sub}_out{_BQ_OUT_EXT.get(sub, '')}")
                out_kind = _task_output_kind(t, sub)
                out_param = _task_output_param(t, sub)
                # Build the leaf spec to get artifact-annotated inputs
                leaf = fnmap.get(expected_fn, {})
                # P0: bqtools subcommand-specific fixture MUST override the
                # generic artifact resolver. encode takes FASTA, consumers
                # take BINSEQ — the generic resolver sees "binseq" on the
                # base tool's input and wrongly applies it to ALL subs.
                if name == "bqtools":
                    if sub in _BQ_INPUT_BINSEQ:
                        param_fixtures = {"input": binseq_sample}
                    else:
                        param_fixtures = {"input": sample}
                else:
                    param_fixtures = _resolve_param_fixtures(leaf)
                if not param_fixtures:
                    param_fixtures = {"input": sample}
                label = f"{name}: {sub} on sample -> {os.path.basename(out)}"
                prompt = _build_subcommand_prompt(
                    expected_fn, name, param_fixtures, out, out_param,
                    sub=sub, pattern_file=pattern_file)
                tasks.append((label, prompt, expected_fn, out, out_kind))
        else:
            expected_fn = name
            out = os.path.join(outdir, f"{name}_out")
            out_kind = _task_output_kind(t)
            out_param = _task_output_param(t)
            # Resolve fixtures from the LEAF ToolSpec (not the raw registry
            # tool which has params_schema, not inputs). fnmap maps function
            # names to the exact leaf ToolSpec that produces the LLM schema.
            leaf_for_fixtures = fnmap.get(expected_fn, t)
            param_fixtures = _resolve_param_fixtures(leaf_for_fixtures)
            label = f"{name}: process sample -> {os.path.basename(out)}"
            prompt = _build_nonsubcommand_prompt(
                name, param_fixtures, out, out_param)
            tasks.append((label, prompt, expected_fn, out, out_kind))

    print(f"\n== {len(tasks)} concrete per-tool tasks ==")
    for label, prompt, ef, op, ok in tasks:
        print(f"  {label}  fn={ef}")
        print(f"    prompt:\n{prompt}")
    for r in skip_reasons:
        print(f"  [skip-task] {r}")
    stats = {"selected": 0, "wrong_function": 0, "started": 0,
             "tool_unavailable": 0,
             "process_ok": 0, "output_valid": 0, "succeeded": 0}
    per_tool = {}
    for label, user_prompt, expected_fn, out_path, out_kind in tasks:
        print(f"\n=== task: {label} ===")
        if os.path.exists(out_path):
            os.remove(out_path)
        messages = [{"role": "user", "content": user_prompt}]
        final = None
        selected = False
        wrong_function = False
        started = False
        # per-task isolation: the retry cap resets for EVERY task, so a tool
        # burned in task A doesn't block the same tool in task B.
        tool_attempts = {}
        target_exited_0 = False   # the TARGET function exited 0 (process-level)
        target_ran = False        # the TARGET function was actually called
        tool_unavailable = False  # timeout, command not found, or resource error
        raw_log = []              # full (fn, argv, rc, stdout, stderr) per call
        # TASK-SCOPED tool selection (P0): the LLM only sees the ONE function
        # this task is about. Exposing every schema lets it pick a random
        # unrelated tool (bqtools_info on a kaptain task -> WRONG_FUNCTION).
        task_tools = [schema_by_name[expected_fn]] if expected_fn in schema_by_name else schemas
        task_start = time.time()
        budget_exceeded = False
        for turn in range(MAX_TURNS):
            if time.time() - task_start > AGENT_TASK_BUDGET:
                budget_exceeded = True
                print(f"[task budget {AGENT_TASK_BUDGET}s exceeded after turn {turn}; stopping task]")
                break
            resp = client.chat.completions.create(
                model=MODEL, messages=messages, tools=task_tools, tool_choice="auto")
            msg = resp.choices[0].message
            if not getattr(msg, "tool_calls", None):
                final = msg.content
                break
            messages.append(msg)
            for tc in msg.tool_calls:
                fn_name = tc.function.name
                args = json.loads(tc.function.arguments or "{}")
                print(f"[turn {turn}] agent chose: {fn_name} args={json.dumps(args)[:120]}")
                selected = True
                if fn_name not in fnmap:
                    result = f"unknown tool {fn_name}"
                else:
                    tool_spec = fnmap[fn_name]  # the EXACT leaf the LLM was shown
                    if fn_name != expected_fn:
                        # P0: calling ANY other tool must NOT count as success,
                        # and it's a test failure the agent should not repeat.
                        wrong_function = True
                        result = (f"[error_type: wrong_function] This task requires the "
                                  f"function `{expected_fn}`. You called `{fn_name}`, which "
                                  f"is the WRONG tool for this task. Do not call it again.")
                        print(f"          result: {result[:120]}")
                        messages.append({"role": "tool", "tool_call_id": tc.id, "content": result})
                        continue
                    if tool_attempts.get(fn_name, 0) >= MAX_SAME_TOOL_ATTEMPTS:
                        # anti-tool-roulette: same tool kept failing -> tell the
                        # agent to STOP retrying it and fix the task differently.
                        result = (f"[tool {fn_name} already tried {tool_attempts.get(fn_name, 0)} times "
                                  f"and kept failing. STOP calling {fn_name}. Fix the argument "
                                  f"values or use a different tool/approach.]")
                    else:
                        tool_attempts[fn_name] = tool_attempts.get(fn_name, 0) + 1
                        # P0: dispatch the SAME leaf ToolSpec that produced the
                        # function schema the LLM saw (fnmap[fn_name]). Its inputs
                        # are scoped to THIS subcommand, so bqtools_encode(input,
                        # output) args validate against the exact schema shown.
                        raw = run_tool_spec(tool_spec, args,
                                            timeout_override=AGENT_CALL_TIMEOUT)
                        result = format_result(raw)
                        target_ran = True
                        # full raw capture (P1: never truncate the real error)
                        raw_log.append({
                            "fn": fn_name, "args": args,
                            "argv": raw.get("argv"), "return_code": raw.get("return_code"),
                            "status": raw.get("status"),
                            "stdout": (raw.get("stdout") or "")[-2000:],
                            "stderr": (raw.get("stderr") or "")[-2000:],
                        })
                        if raw.get("argv"):
                            print(f"          argv: {raw['argv']}")
                            print(f"          exit: {raw.get('return_code')}")
                        # P0: process success is ONLY the target function exiting 0
                        if raw.get("return_code") == 0 and raw.get("status") == "ok":
                            target_exited_0 = True
                        if raw.get("return_code") not in (127,):
                            started = True
                        # detect runtime resource unavailability
                        stderr_l = (raw.get("stderr") or "").lower()
                        if raw.get("return_code") is None:
                            # subprocess.TimeoutExpired → return_code=None
                            tool_unavailable = True
                        elif raw.get("return_code") == 127:
                            tool_unavailable = True
                        elif any(kw in stderr_l for kw in [
                            "database not present", "database not found",
                            "database not available", "not installed",
                            "command not found", "no such file",
                        ]):
                            tool_unavailable = True
                    low = result.lower()
                print(f"          result: {result[:150]}")
                messages.append({"role": "tool", "tool_call_id": tc.id, "content": result})

        # ---- output validation by the task's declared output contract ----
        # P1: exit 0 (process) and TASK_SUCCEEDED (output produced) are separate.
        # An output DIRECTORY is valid only if it's a dir with contents.
        if target_exited_0:
            process_ok = True
            if out_kind == "directory":
                output_ok = (os.path.isdir(out_path)
                             and bool(os.listdir(out_path)))
            elif out_kind == "file":
                output_ok = (os.path.isfile(out_path)
                             and os.path.getsize(out_path) > 4)
            else:  # stdout-only tool: exit 0 + real STDOUT output is the bar
                last = raw_log[-1] if raw_log else {}
                # stderr logs ("INFO: done") are NOT the deliverable when the
                # contract says stdout -- exit 0 + empty stdout is OUTPUT_INVALID
                output_ok = bool((last.get("stdout") or "").strip())
        else:
            process_ok = False
            output_ok = False

        if target_exited_0 and output_ok:
            status = "TASK_SUCCEEDED"
        elif target_exited_0:
            status = "OUTPUT_INVALID"
        elif tool_unavailable:
            status = "TOOL_UNAVAILABLE"
        elif target_ran:
            status = "PROCESS_FAILED"
        elif wrong_function:
            status = "WRONG_FUNCTION"
        elif started:
            status = "TOOL_STARTED"
        elif selected:
            status = "TOOL_SELECTED"
        else:
            status = "NOT_SELECTED"
        per_tool[label] = {
            "expected_fn": expected_fn,
            "selected": selected, "wrong_function": wrong_function,
            "target_ran": target_ran, "target_exited_0": target_exited_0,
            "tool_unavailable": tool_unavailable,
            "process_ok": process_ok, "output_ok": output_ok,
            "output_kind": out_kind, "status": status,
            "calls": raw_log,
        }
        if selected: stats["selected"] += 1
        if wrong_function: stats["wrong_function"] += 1
        if started: stats["started"] += 1
        if tool_unavailable: stats["tool_unavailable"] += 1
        if process_ok: stats["process_ok"] += 1
        if output_ok: stats["output_valid"] += 1
        if status == "TASK_SUCCEEDED": stats["succeeded"] += 1
        print(f"  => {status}")

    print(f"\n== agent tool-usage summary ==")
    n = len(tasks)
    print(f"  tasks:                 {n}")
    print(f"  tool selected:         {stats['selected']}/{n}")
    print(f"  wrong function:        {stats['wrong_function']}/{n}")
    print(f"  tool started (ran):    {stats['started']}/{n}")
    print(f"  tool unavailable:      {stats['tool_unavailable']}/{n}")
    print(f"  target exit 0:         {stats['process_ok']}/{n}")
    print(f"  output valid:          {stats['output_valid']}/{n}")
    print(f"  TASK_SUCCEEDED:        {stats['succeeded']}/{n}")
    print("  (success = TARGET function exit 0 + valid output; any other tool")
    print("   exiting 0 is recorded as WRONG_FUNCTION, NOT success)")
    print("  TOOL_UNAVAILABLE = timeout / command not found / missing runtime resource")
    # persist the FULL per-call detail (argv/stdout/stderr, untruncated) so a
    # failure is debuggable instead of being cut at 150 chars in the console.
    out_json = os.environ.get("AGENT_TEST_JSON", "")
    if out_json:
        import json as _json
        with open(out_json, "w", encoding="utf-8") as f:
            _json.dump({"schemas": [s["function"]["name"] for s in schemas],
                        "tasks": per_tool}, f, ensure_ascii=False, indent=2)
        print(f"full detail -> {out_json}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
